# Generated by Django 2.1.7 on 2019-02-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
