# Generated by Django 2.1.7 on 2019-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190213_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comment',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to='index/static/image'),
        ),
    ]
