# Generated by Django 2.1.7 on 2019-02-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190213_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='judul',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='konten',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='harga',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keterangan',
            field=models.TextField(default='0', max_length=25),
        ),
    ]
