# Generated by Django 2.1.5 on 2019-02-11 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0002_auto_20190211_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_kunjung',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
