# Generated by Django 2.1.7 on 2019-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20190213_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
