# Generated by Django 2.1.5 on 2019-02-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.DateTimeField(),
        ),
    ]
