# Generated by Django 2.1.5 on 2019-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0002_auto_20190211_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='telepon',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='obat',
            name='kandungan',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obat',
            name='khasiat',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='telepon',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='resep',
            name='total_harga',
            field=models.CharField(max_length=25),
        ),
    ]
